[package]
name = "playfair-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "playfair"
path = "src/main.rs"

[dependencies]
playfair-core = { workspace = true }
memmap2 = { workspace = true }
clap = { version = "4.4.7", features = ["derive"] }
